#!/bin/bash

# Read PEM-formatted certificate data from the supplied file, or
# stdin. Remove blanks, append/prepend BEGIN/END lines if missing, and
# lob the result at 'openssl x509' with some helpful formatting
# options

DATA=$(sed 's/^ *//' ${1})

#echo "${DATA}" | cat

if [ "${DATA:0:10}" != "-----BEGIN" ]; then
  DATA=$'-----BEGIN CERTIFICATE-----\n'${DATA}$'\n-----END CERTIFICATE-----\n'
fi

#echo "${DATA}" | cat

echo "${DATA}" | openssl x509 -noout -text -nameopt esc_ctrl,esc_msb,space_eq,sep_multiline -certopt no_header,no_sigdump

echo ""

echo "${DATA}" | openssl x509 -noout -fingerprint -md5
echo "${DATA}" | openssl x509 -noout -fingerprint -sha1 
echo "${DATA}" | openssl x509 -noout -fingerprint -sha256 



